# Generated by Django 3.2.7 on 2021-11-08 11:24

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=80, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Отчество')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='Фото профиля')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Токен')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Мобильный')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место расположения')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Не указан'), (1, 'Мужской'), (2, 'Женский')], null=True, verbose_name='Пол')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пользователь активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход в систему')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]