# Generated by Django 3.1 on 2021-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noseriesline',
            name='ending_no',
            field=models.CharField(max_length=20, verbose_name='Конечный Но'),
        ),
        migrations.AlterField(
            model_name='noseriesline',
            name='last_no_used',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Посл.Исп. Но'),
        ),
        migrations.AlterField(
            model_name='noseriesline',
            name='warning_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Предупредительный Но'),
        ),
    ]
