# Generated by Django 3.1 on 2021-01-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20210121_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noseriesline',
            name='series_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noseriesline', to='settings.noseries', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код Типа Услуг'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код Ед. Измерения'),
        ),
        migrations.AlterField(
            model_name='vatpostinggroup',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код Учетной Группы'),
        ),
        migrations.CreateModel(
            name='BillingSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('service_no_series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noseriesline', to='settings.noseriesline', verbose_name='Услуга Серия Номеров')),
            ],
            options={
                'verbose_name': 'Биллинг Настройка',
                'verbose_name_plural': 'Биллинг Настройки',
                'db_table': 'billing_setup',
            },
        ),
    ]
