# Generated by Django 3.1 on 2020-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, verbose_name='Название терминала')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'терминалы',
                'db_table': 'terminal',
            },
        ),
    ]
