# Generated by Django 3.1 on 2020-09-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportconf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['name'], 'verbose_name': 'Терминал', 'verbose_name_plural': 'терминалы'},
        ),
    ]
